version: '3.8'

services:
  nginx:
    container_name: nginx_${APP_NAME}
    build:
      context: .
      dockerfile: nginx.prod.dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:${WEB_DIR}
    depends_on:
      - mysql
      - php
      - assets
  php:
    container_name: php_${APP_NAME}
    build:
      context: .
      dockerfile: php.prod.dockerfile
    volumes:
      - ./src:${WEB_DIR}
  assets:
    container_name: assets_${APP_NAME}
    image: node:current-alpine
    volumes:
      - ./src:${WEB_DIR}
    command: [ "/bin/sh", "-c", "npm install && npm run production" ]
    working_dir: ${WEB_DIR}/current
